---
# roles/containerd/tasks/main.yml
- name: system
  debug:
    msg: "System {{ inventory_hostname }}" 
  tags: always
 
- name: Install Containerd
  import_tasks: install_containerd.yml
  when: "'install_containerd' in ansible_tags or 'all' in ansible_tags or (ansible_tags is undefined) or ansible_tags|default([])|length == 0"

- name: Install crictl
  import_tasks: install_crictl.yml
  when: "'install_crictl' in ansible_tags or 'all' in ansible_tags or (ansible_tags is undefined) or ansible_tags|default([])|length == 0"


- name: Uninstall Containerd
  import_tasks: uninstall_containerd.yml
  when: "(ansible_tags is defined) and ('uninstall_containerd' in ansible_tags or 'remove' in ansible_tags)"

- name: Uninstall crictl
  import_tasks: uninstall_crictl.yml
  when: "(ansible_tags is defined) and ('uninstall_crictl' in ansible_tags or 'remove' in ansible_tags)"
