apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: spectrum-scale-fileset
    volume.beta.kubernetes.io/storage-provisioner: ubiquity/flex
  name: test-pvc-cbates
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
