apiVersion: 1
kind: Deployment
metadata:
  name: elk
  tags:
    app: elk
spec:
  replicas: 1
  containers:
    - name: elk
      image: sebp/elk:6.3.2
      ports:
        - containerPort: 5601
        - nodePort: 
        
        EXPOSE 5601 9200 9300 5044
VOLUME /var/lib/elasticsearch
 -e LOGSTASH_START=0 -e KIBANA_START=0
 
 # https://elk-docker.readthedocs.io/
 
 apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 3 
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
        
   volumeMounts:
      - name: registry-data-pvc
        mountPath: /var/lib/registry
  volumes:
  - name: registry-data-pvc
    persistentVolumeClaim:
      claimName: docker-registry-pvc
 
 
    
