kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "spectrum-scale-fileset"
#    volume.beta.kubernetes.io/storage-provisioner: ubiquity/flex
  name: "elk-elasticsearch-data-pvc"
  namespace: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
