apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: elk-deployment
  namespace: elasticsearch
spec:
  selector: 
    matchLabels: 
      app: elk
  replicas: 1
  template:
    metadata: 
      labels:
        app: elk
    spec:
      containers:
      - name: elk
        image: sebp/elk:6.3.2
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 9300
        - containerPort: 5044
        volumeMounts:
        - name: elk-elasticsearch-data-pvc
          mountPath: /var/lib/elasticsearch
        env:
        - name: LOGSTASH_START
          value: "0"
        - name: KIBANA_START
          value: "1"
      volumes:
      - name: elk-elasticsearch-data-pvc
        persistentVolumeClaim:
          claimName: elk-elasticsearch-data-pvc
 
 
    
