apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app:  busybox
spec:
  containers:
  - image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: sharedstorage
      mountPath: /data
  restartPolicy: Always
  nodeSelector:
    name: compute1
  volumes:
  - name: sharedstorage
    persistentVolumeClaim:
      claimName: example-pod-pv-pvc-rwx
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: sharedstorage
      mountPath: /data
  restartPolicy: Always
  nodeSelector:
    name: compute2
  volumes:
  - name: sharedstorage
    persistentVolumeClaim:
      claimName: example-pod-pv-pvc-rwx
