kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: alert-emailer
      email_configs:
      - to: test@gmail.com
        send_resolved: false
        from: k8smon@gmail.com
        smarthost: smtp@gmail.com
        auth_username: test@gmail.com
        auth_identity: test@gmail.com
        require_tls: true
        auth_password:
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/...
        channel: '#k8scluster'
