apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: prometheus-pv
  labels:
    volumeName.dory: prometheus-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: sc-hpe
