# main
---

 - name: Install base packages
   yum:
     name: "{{ packages }}"
     state: latest
   vars:
     packages:
      - python-pip
      - python3-pip
   register: common_yum_install

 - name: Upgrade pip
   pip: name=pip state=latest
   tags:
    - packages
