apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  clusterIP: 35.168.2.59
  ports:
  - name: http
    port: 8080
    nodePort: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
