# Flannel
---

 - name: Install Flannel
   shell: |
     kubectl apply -f \
     https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml
   args:
     executable: /bin/bash
   register: install_flannel_result
   tags: 
    - flannel-install

 - debug:
    msg: "{{ install_flannel_result }}"

