# Flannel
---

 - name: Install Flannel
   shell: |
     kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
   args:
     executable: /bin/bash
   register: install_flannel_result
   tags: 
    - flannel-install

 - debug:
    msg: "{{ install_flannel_result }}"

