apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testvol2-pv
  labels:
    volumeName.dory: testvol2-k8s
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-hpe
