--- # This is an example to install HTTPD on Centos
- hosts: '{{ hosts }}'   # generally a node setup in /etc/hosts
  remote_user: ansible
  become: yes     # become root
  become_method: sudo  # in general, don't assume defaults.  Specify!
  connection: ssh
  gather_facts: yes
  vars:
    username: apache
  tasks:
   - name: Install HTTPD on Centos7 nodes
     yum:
      name: httpd
      state: latest
     notify: # upon success, run the following handler
      - startservice
  handlers:
   - name: startservice
     service:
       name: httpd
       state: restarted #or start if the first time
