---
- hosts: '{{ hosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
   - playbook_version: 0.1 
     hosts: nodes
  vars_files:
   - ../conf/k8s_env.yml
   - ../conf/docker_env.yml
   - ../conf/multus.yml
  tasks:
   - debug: msg="DHCP range lookup for node c1 {{ lookup('csvfile','c1 file=../conf/multus-sriov-dhcp.csv delimiter=, col=1  default=NOMATCH') }}"
  
   - name: check if Multus CNI file exists 
     stat: 
       path: "{{ k8s_cni_bin_path }}/multus-cni"
     register:  k8s_cni_bin_multus
     async: 10
     poll: 3
   - debug: var=k8s_cni_bin_multus

   - name: Download Multus CNI
     delegate_to: localhost
     get_url:
       url: '{{ multus_download_url }}' 
       dest: /tmp
       mode: 0440
     register: k8s_cni_bin_multus_archive
     when: k8s_cni_bin_multus.stat.exists == false

   - debug: var=k8s_cni_bin_multus_archive
     delegate_to: localhost

   # Extract the CNI binary
   - name: Extract Multus CNI Binary
     delegate_to: localhost
     unarchive:
       src: "/tmp/{{ multus_archive_name }}.tar.gz"
       dest: /tmp
       mode: 0440
     register: k8s_cni_bin_multus_extracted
     when: k8s_cni_bin_multus_archive.status_code == 200

   - debug: var=k8s_cni_bin_multus_extracted
     delegate_to: localhost
  
   # copy is expecting the file to be on localhost 
   - name: Copy Multus Bin
     copy: 
       src: "/tmp/{{ multus_archive_name }}/{{ multus_binary_name }}"
       dest: "{{ k8s_cni_bin_path }}"
       owner: root
       group: root
       mode: 0774
     when: k8s_cni_bin_multus_extracted.changed == true
     register: k8s_cni_bin_multus_copy

   - debug: var=k8s_cni_bin_multus_copy
     delegate_to: localhost 
  

# CNI configs go here:  /etc/cni/net.d/
# multus config here, design with template module to inject variables
#- name: Copy Multus CNI Configuration with template 
#  template: 
#    src: 
#    dest: /etc/cni/net.d/
#    backup: yes
    
    

# k8s command execution
#
# rdma-sriov-node-config.yml
#device-plugin.yml
#k8s-sriov-cni-installer.yml
