apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: local-storage
      mountPath: /data
  restartPolicy: Always
  volumes:
  - name: local-storage
    persistentVolumeClaim:
      claimName: pvc-local-data1
  
