apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
