kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
    "name": "multus-cni-network",
    "type": "multus",
    "delegates": [
      {
        "type": "flannel",
        "name": "flannel.1",
        "delegate": {
          "isDefaultGateway": true
        }
      }
    ],
    "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
