apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alpine-sleeper
  labels: 
    lab: linuxacademy
spec:
  selector:
    matchLabels:
      run: alpine-sleeper
  replicas: 1
  template:
    metadata:
      labels:
        run: alpine-sleeper     
    spec:
      containers:
      - name: alpine-sleeper
        image: alpine:latest
        command: ["/bin/ash"]
        args: ["-c","sleep 60"]
      restartPolicy: Always
      nodeSelector:
        net: gigabit

