# k8s-node/tasks/main.yml
---
# - name: Populate service facts
#   service_facts:
# - debug: var=ansible_facts.services['kubelet']
- name: Reset kubeadm before init in case this is not the first run
  command: kubeadm reset -f
  when: k8s_reset_before_init
  tags: 
   - node-install

# Execute the join cmd
- name: Run joincmd script
  script: "{{ k8s_joincmd_file }}" 
  tags: 
   - node-install 
