# k8s-node/tasks/main.yml
---
# - name: Populate service facts
#   service_facts:
# - debug: var=ansible_facts.services['kubelet']



- name: start_kubelet_handler
  service:
    name: kubelet
    state: restarted
