apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: "rabbitmq:3-management"
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "rootTesting"
            - name: RABBIT_PASSWORD
              value: "25Testing01"
          ports:
            - containerPort: 5672
              name: rabbitmq
            - containerPort: 15672
              name: web-rabbitmq

