# This install creates 2 pods with nodeSelectors for where to place the pods.
# Label two nodes node 1 and node 2.  From here, you can exec into one and ping the other.
#
# Enable scheduling on master:  kubectl taint node `hostname`  node-role.kubernetes.io/master:NoSchedule-
#
# Label a node: kubectl label nodes <node-name> name=node1
# and view the labels: kubectl get nodes --show-labels 
# 
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeSelector:
    name: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeSelector:
    name: node2
