# multus-cni main.yml
---
#Copy 10-multus.conf to /etc/net.d/cni after substituting variables for
#10. network segment for the host into the config File


#Copy multus-bin to /opt/bin/cni from ansible controller (localhost)
# - need to do this because of the install environment
# - requires download from github Project
#
 - name: check if Multus CNI file exists
   stat:
     path: "{{ k8s_cni_bin_dir }}/{{ k8s_cni_multus_binary_name }}"
   register:  k8s_cni_bin_multus
 - debug: var=k8s_cni_bin_multus

 - name: check if Multus CNI archive exists locally
   delegate_to: 127.0.0.1
   stat:
     path: "{{ tmp_dir }}/{{ k8s_cni_multus_archive_name }}"
   register: k8s_cni_multus_archive
 - debug: var=k8s_cni_multus_archive

 - name: Download Multus CNI Locally
   delegate_to: 127.0.0.1
   get_url:
     url: '{{ k8s_cni_multus_download_url }}'
     dest: '{{ tmp_dir }}'
     mode: 0440
   register: k8s_cni_multus_archive
   when: k8s_cni_multus_archive.stat.exists == false
 - debug: var=k8s_cni_multus_archive

 - name: stat of extracted Multus CNI binary
   stat:
     path: "{{ remote_tmp_dir }}/{{ k8s_cni_multus_archive_name }}"
   register: k8s_cni_multus_archive_extracted
 - debug: var=k8s_cni_multus_archive_extracted

 # Extract the CNI binary now on the target host
 - name: Extract Multus CNI Binary on nodes
   unarchive:
     src: "{{ tmp_dir }}/{{ k8s_cni_multus_archive_name }}.tar.gz"
     dest: "{{ remote_tmp_dir }}"
     mode: 0440
   when: k8s_cni_multus_archive_extracted.stat.exists == false
   register: k8s_cni_multus_archive_extracted
 - debug: var=k8s_cni_multus_archive_extracted

 # copy is expecting the file to be on localhost
 - name: Copy Multus Bin
   copy:
     remote_src: yes
     src: "{{ remote_tmp_dir }}/{{ k8s_cni_multus_archive_name }}/{{ k8s_cni_multus_binary_name }}"
     dest: "{{ k8s_cni_bin_dir }}"
     owner: {{ k8s_system_user }}
     group: {{ k8s_system_group }}
     mode: 0774
   #when: k8s_cni_bin_multus.stat.exists == false
   register: k8s_cni_bin_multus_copy
 - debug: var=k8s_cni_bin_multus_copy
