# Install multus config
---
 # Using the group_vars for k8s, create networks for sr-iov ib0 interfaces and deploy them
 - name: Check stat of multus config file
   stat:
     path: "{{ k8s_cni_config_dir }}/{{ k8s_cni_multus_config_filename }}"
   register: k8s_cni_multus_config
 - debug: var=k8s_cni_multus_config

 # Display the extracted inventory_hostname var - the name of the host
 # this instance is running on
 - debug: var=inventory_hostname

# Will always run and overwrite any existing config
 - name: Install Multus CNI config for SR-IOV and flannel
   template:
     src: "{{ k8s_cni_multus_config_template }}"
     dest: "{{ k8s_cni_config_dir }}/{{ k8s_cni_multus_config_filename }}"
     owner: "{{ k8s_system_user }}"
     group: "{{ k8s_system_group }}"
     mode: 0750
   register: k8s_cni_multus_config_template
 - debug: var=k8s_cni_multus_config_template
