# k8s install
---
- name: Bootstrap Tasks
  hosts: docker
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: False
  become: yes
  become_method: sudo
  connection: ssh
  roles:
   - common
   - docker

