# k8s install
---
- name: Install k8s binaries
  hosts: k8s
 # gather_facts: True
  become: yes
  roles:
    - k8s

- name: Install k8s master
  hosts: master
  become: yes
  roles:
    - k8s-master
    - calico
  
- name: Install K8s Nodes
  hosts: node
  become: yes
  roles:
    - k8s-node
