# k8s install Prometheus
---
- name: Install Prometheus
  hosts: prometheus
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: True
  become: yes
  become_method: sudo 
  connection: ssh
  roles:
    - prometheus
