# k8s install
---
- name: Install k8s
  hosts: k8s
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: True
  become: yes
  become_method: sudo
  connection: ssh
  roles:
    - k8s

- name: Install k8s master
  hosts: master
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: True
  become: yes
  become_method: sudo
  connection: ssh
  roles:
    - k8s-master
    - flannel


- name: Install K8s Nodes
  hosts: node
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: True
  become: yes
  become_method: sudo
  connection: ssh
  roles:
    - k8s-node
