# k8s-uninstall.yml
---
- name: Uninstall k8s
  hosts: master:node
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: True
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
   - include_role:
       name: k8s
       tasks_from: stop
   - include_role:
       name: k8s
       tasks_from: uninstall
   - include_role:
       name: docker
       tasks_from: prune_all
#   - name: k8s-mlx-sriov uninstall
#     include_role:
#       name: k8s-mlx-sriov
#       tasks_from: uninstall
#   - name: k8s-multus uninstall
#     include_role:
#       name: k8s-multus
#       tasks_from: uninstall
