apiVersion: v1
kind: Namespace
metadata:
  name: nginxscp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginxscp-serviceaccount
  namespace: nginxscp
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginxscp-rolebindingcluster
subjects:
  - kind: ServiceAccount
    name: nginxscp-serviceaccount
    namespace: nginxscp
roleRef:
  kind: ClusterRole
  name: system:node-bootstrapper 
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-approve-csrs-for-nginxscp-serviceaccount
subjects:
- kind: ServiceAccount
  name: nginxscp-serviceaccount
  namespace: nginxscp
roleRef:
  kind: ClusterRole
  name: system:certificates.k8s.io:certificatesigningrequests:nodeclient
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginxscp-deployment
  namespace: nginxscp
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sidecar
  template:
    metadata:
      name: nginxscp-pod
      namespace: nginxscp
      labels:
        app: nginx-sidecar
    spec:
      restartPolicy: Always
      serviceAccountName: nginxscp-serviceaccount
      containers:
      - image: meadowgate/qat-centos7:1.0
        name: nginxscp
        securityContext:
          privileged: true
          capabilities:
            add:
              [SYS_ADMIN]
        volumeMounts:
                - mountPath: /dev
                  name: dev-mount
                - mountPath: /etc/c6xxvf_dev0.conf
                  name: dev0
        resources:
          requests:
            qat.intel.com/generic: '1'
            memory: 3Gi
            hugepages-2Mi: 2Gi
          limits:
            qat.intel.com/generic: '1'
            memory: 3Gi
            hugepages-2Mi: 2Gi
        ports:
          - containerPort: 443
        command: ["/bin/sh", "-c" , "/init.sh && while true ; do sleep 30000; done"]
      - image: mlabbe/iperf
        name: iperf2-container
      volumes:
      - name: dev-mount
        hostPath:
            path: /dev
      - name: dev0
        hostPath:
            path: /etc/c6xxvf_dev0.conf
      nodeName: minikube
