apiVersion: v1
kind: Pod
metadata:
  name: nginxproxied-pod
spec:
  restartPolicy: OnFailure
  containers:
  - image: meadowgate/qat-centos7:1.0
    name: nginx-sidecar
    securityContext:
      privileged: true
    resources:
      requests:
        qat.intel.com/generic: 2
        memory: 2Gi
        hugepages-2Mi: 2Gi
      limits:
        qat.intel.com/generic: 2
        memory: 3Gi
        hugepages-2Mi: 2Gi
    ports:
      - containerPort: 443
    command: ["/bin/sh", "-c" , "/build/init.sh && while true ; do sleep 1000 ; done"]
  nodeName: minikube
