# k8s-master/tasks/main.yml
# Help from: https://github.com/magic7s/ansible-kubeadm-contiv/blob/master/roles/master/tasks/main.yml
---
- name: Resest Kubeadm if first run
  command: /usr/bin/kubeadm reset
  when: k8s_reset_before_init
