# k8s-master/tasks/main.yml
# Help from: https://github.com/magic7s/ansible-kubeadm-contiv/blob/master/roles/master/tasks/main.yml
---
- name: Resest Kubeadm if first run
  command: kubeadm reset -f
  when: kubeadm_reset_before_init
  tags: k8s_master_install

- name: disable Swap
  command: "swapoff -a"
  tags: k8s_master_install

- name: Stop kubelet if running
  service:
    name: kubelet
    state: stopped
  tags: k8s_master_install

- name: create kube dir
  file:
    path: /etc/kubernetes
    state: directory
    owner: root
    group: root
    force: yes
    mode: 0700
  tags: k8s_master_install

- name: kubeadm init
  command: "/usr/bin/kubeadm init \
   --ignore-preflight-errors={{ preflight_errors | quote }} \
   --pod-network-cidr={{ k8s_kubelet_service_cidr }}"
  register: kubeadm_init_result
- debug: var=kubeadm_init_result
  tags: k8s_master_install

- name: wait for k8s to start
  wait_for:
    port: 6443
    delay: 10
    timeout: 300
  register: k8s_state_started
  tags: k8s_master_install

- name: copy config file to root/.kube dir
  copy:
    dest: /etc/kubernetes/admin.conf
    src: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    force: yes
    mode: 0400
  when: k8s_state_started
  tags: k8s_master_install

- name: taint master node
  command: "kubectl \
  --kubeconfig /etc/kubernetes/admin.conf \
  taint nodes --all node-role.kubernetes.io/master-"
  when: k8s_state_started
  tags: k8s_master_install

- name: allow permissive RBAC rules
  command: "kubectl \
  --kubeconfig /etc/kubernetes/admin.conf create clusterrolebinding \
  permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts"
  when: k8s_state_started
  tags: k8s_master_install


#- pause:
#    minutes: 1
#    prompt: "Make sure network pods are started"
