# K8s
---
- name: Add k8s yum repository
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  tags: [ k8s-install, install k8s-repo ]  


# Install k8s binaries
- name: Install k8s
  dnf:
    name: "{{ packages }}"
    state: installed
  vars:
    disable_excludes: "kubernetes"
    packages:
     - "kubelet"
     - "kubeadm"
     - "kubectl"
  register: k8s_yum_install
  tags: [ k8s-install install k8s-repo ]

# notify: start_kubelet_handler
- debug: var=k8s_yum_install
  
