# k8s/tasks/uninstall
---
- name: Uninstall k8s
  yum:
    name: "{{ packages }}"
    state: removed
  vars:
    packages:
     - "kubelet"
     - "kubeadm"
     - "kubectl"
     - "kubernetes-cni"
  register: k8s_yum_uninstall
- debug: var=k8s_yum_uninstall
