# install Mellanox SRIOV Daemonset
---
 - name:  Install Mellanox SR-IOV Daemonset
   k8s_raw:
     state: present
     definition: "{{ lookup('template', 'sriov-cni-daemonset.yml.j2') | sriov-cni-daemonset.yml }}"
   register: k8s_raw_present_sriov-cni-daemonset
 - debug: var=k8s_raw_present_sriov-cni-daemonset
